### ISSUE TITLE
`ctrl-alt-shift-up` doesn't seem to work

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/keymaps#13]
For instance, in the JetBrains keymap, the following action doesn't work

`"ctrl-alt-shift-up": "editor::GoToPrevHunk"`

**Comment by JosephTLyons** [comment]
It turns out, my window manager ([Rectangle Pro](https://rectangleapp.com/pro)) was silently consuming this keybindings.  After quitting the app, command worked as expected.

**Comment by JosephTLyons** [comment]
@ForLoveOfCats, I know you mentioned this command not working for you as well.  Can you disable whatever window management software you might be using and try again?

**Comment by ForLoveOfCats** [comment]
Yup same situation on my system haha

![CleanShot 2023-01-01 at 01 53 41](https://user-images.githubusercontent.com/30666851/210163150-430896f0-1c44-4fd1-b532-334ac391e0d4.png)
